### ISSUE TITLE
Passing gcc complier flags to clang

### ISSUE THREAD

**Issue by alexisrozhkov** [BOOtak/android-ollvm-sample#1]
Trying to build this example in latest Android Studio I first get an error:
`.../android-ollvm-sample/app/build/tools/llvm_obfuscator/bin/clang++: not found`

I assume that although the description says the project is `aimed to show how to download and compile llvm-obfuscator via CMake` I have to download the prebuilt llvm-obfuscator and place it in the specified directory manually.

After doing it, Android Studio is able to locate clang, and starts to complain about:
`Error:error: unknown argument: '-fstack-protector-strong'` and
`Error:error: unknown argument: '-fno-integrated-as'`

From what I understand it's caused by passing gcc-specific flags to clang toolchain. 

Is there any way to build this project using up to date versions of tool? Maybe I'm missing some steps?

**Comment by BOOtak** [comment]
Hi, sorry I missed your issue, I'll test this code today and probably find a way to fix this.

**Comment by BOOtak** [comment]
OK. I've re-checked and fixed some errros. Also I should mention that for proper llvm-obfuscator build from source you should have git and patch utilities. and you should have name and email set in git config for proper llvm-obfuscator repository sync.
To make sure everything works, I need you to re-import project, clean and build it again. If it does not work, please, copy output of gradle console to gist and put link to it here

**Comment by BOOtak** [comment]
@alexisrozhkov OK, I'll close this issue for now, as some errors were fixed, try this again and feel free to open a new issue if something goes wrong
